spring:
  application:
    name: zuul-server
server:
  port: 8002
eureka:
  instance:
    preferIpAddress: true
    instance-id: 183.131.202.13:${spring.application.name}:${server.port}
    # 超过这个时间没有心跳，eurekaserver 删除该服务
    lease-expiration-duration-in-seconds: 90
    # 每隔30秒与注册中心心跳一次
    lease-renewal-interval-in-seconds: 30
  client:
    healthcheck:
      enabled: true
    # 刷新本地缓存
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://183.131.202.13:8000/eureka/
zuul:
  routes:
    eureka-server:
      path: /api-eureka/**
      serviceId: eureka-server
    config-server:
      path: /api-config/**
      serviceId: config-server
    approve-server:
      path: /approve-server/**
      serviceId: approve-server
    coupon-server:
      path: /coupon-server/**
      serviceId: coupon-server
    CRM-server:
      path: /CRM-server/**
      serviceId: CRM-server
    crmroute-server:
      path: /crmroute-server/**
      serviceId: crmroute-server
    deliver-server:
      path: /deliver-server/**
      serviceId: deliver-server
    evaluate-server:
      path: /evaluate-server/**
      serviceId: evaluate-server
    group-server:
      path: /group-server/**
      serviceId: group-server
    integration-server:
      path: /integration-server/**
      serviceId: integration-server
    mall-server:
      path: /mall-server/**
      serviceId: mall-server
    marketing-server:
      path: /marketing-server/**
      serviceId: marketing-server
    medical-server:
      path: /medical-server/**
      serviceId: medical-server
    order-server:
      path: /order-server/**
      serviceId: order-server
    pay-server:
      path: /pay-server/**
      serviceId: pay-server
    prepaidcard-server:
      path: /prepaidcard-server/**
      serviceId: prepaidcard-server
    setting-server:
      path: /setting-server/**
      serviceId: setting-server
    user-server:
      path: /user-server/**
      serviceId: user-server