mybatis:
  mapper-locations: mapper/*.xml
spring:
  application:
    name: zuul-server
  datasource:
    enable: true
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://183.131.202.186:3306/CRM?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: wanbo@123
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  kafka:
    bootstrap-servers: 183.131.202.13:9092
    producer:
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 8002
