mybatis:
  mapper-locations: mapper/*.xml
spring:
  application:
    name: zuul-server
  datasource:
    enable: true
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://183.131.202.13:3300/zuul?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: lindj
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
server:
  port: 8002