spring:
  application:
    name: zuul-server
server:
  port: 8002
eureka:
  instance:
    preferIpAddress: true
    instance-id: 183.131.202.13:${spring.application.name}:${server.port}
    # 超过这个时间没有心跳，eurekaserver 删除该服务
    lease-expiration-duration-in-seconds: 90
    # 每隔30秒与注册中心心跳一次
    lease-renewal-interval-in-seconds: 30
  client:
    healthcheck:
      enabled: true
    # 刷新本地缓存
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://183.131.202.13:8000/eureka/
zuul:
  routes:
    provider-service:
      path: /provider-service/**
      serviceId: provider-service
    approve-server:
      path: /approve-server/**
      serviceId: approve-server