spring:
  application:
    name: consumer-service
server:
  port: 8002
eureka:
  instance:
    # 超过这个时间没有心跳，eurekaserver 删除该服务
    lease-expiration-duration-in-seconds: 90
    # 每隔30秒与注册中心心跳一次
    lease-renewal-interval-in-seconds: 30
  client:
    healthcheck:
      enabled: true
    # 刷新本地缓存
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
ribbon:
  # ribbon刷新时间
  ServerListRefreshInterval: 30000
feign:
  hystrix:
    enabled: true