mybatis-plus:
  mapper-locations: mapper/*.xml
spring:
  application:
    name: log-server
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://183.131.202.186:3306/log?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: wanbo@123
    druid:
      initial-size: 5
      max-active: 8
      min-idle: 0
      max-wait: -1
      query-timeout: 10
      validation-query: SELECT 1
      use-global-data-source-stat: true
      # 开启 StatFilter，默认开启，可通过 'enabled: false' 关闭
      stat:
        enabled: true
        log-slow-sql: true
        slow-sql-millis: 10000
      # 开启 Slf4jFilter
      slf4j:
        enabled: true
        data-source-log-enabled: false
        connection-log-enabled: false
        statement-log-enabled: false
        result-set-log-enabled: false
      # 开启 WallFilter
      wall:
        enabled: true
        log-violation: true
        throw-exception: false
        ## WallConfig 配置
        config:
          delete-where-none-check: true
      # 开启 Web 监控
      web-stat:
        enabled: true
      # 开启 Aop 监控
      aop-stat:
        enabled: true
      # 开启监控页面
      stat-view-servlet:
        enabled: true
  kafka:
    bootstrap-servers: 183.131.202.13:9092
    # 指定默认消费者group id
    consumer:
      group-id: test
      enable-auto-commit: true
      auto-commit-interval: 100
      # 指定消息key和消息体的编解码方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  port: 8002
constants:
  writeMapExpire: 180
  readMapExpire: 30
  writeMapSize: 1000
  threadPool:
    enable: true
    corePoolSize: 10
    maxPoolSize: 100
    queueCapacity: 10


endpoints:
  druid:
    enabled: true
