spring:
  application:
    name: eureka-server
server:
  port: ${SERVER_PORT}
eureka:
  server:
    # 关闭自我保护
    enable-self-preservation: false
    # readOnlyMap 过期时间
    responseCacheUpdateIntervalMs: 30000
    # 清理间隔时间
    eviction-interval-timer-in-ms: 60000
  instance:
    hostname: ${EUREKA_HOST}
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
  client:
    #是否将自己这个服务注册到EurekaServer中  默认True 此服务为Server
    registerWithEureka: true
    #是否从EurekaServer获取注册信息 默认True 单点ES不存在其他的EurkaServer,所以为False
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SLAVE_URL}:${EUREKA_SLAVE_PORT}/eureka/
