mybatis-plus:
  mapper-locations: mapper/*.xml
spring:
  application:
    name: account-server
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://183.131.202.13:3306/account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Wanbo@123
    druid:
      initial-size: 5
      max-active: 8
      min-idle: 0
      max-wait: -1
      query-timeout: 10
      validation-query: SELECT 1
      use-global-data-source-stat: true
      # 开启 StatFilter，默认开启，可通过 'enabled: false' 关闭
      stat:
        enabled: true
        log-slow-sql: true
        slow-sql-millis: 10000
      # 开启 Slf4jFilter
      slf4j:
        enabled: true
        data-source-log-enabled: false
        connection-log-enabled: false
        statement-log-enabled: false
        result-set-log-enabled: false
      # 开启 WallFilter
      wall:
        enabled: true
        log-violation: true
        throw-exception: false
        ## WallConfig 配置
        config:
          delete-where-none-check: true
      # 开启 Web 监控
      web-stat:
        enabled: true
      # 开启 Aop 监控
#      aop-stat:
#        enabled: true
      # 开启监控页面
#      stat-view-servlet:
#        enabled: true
server:
  port: 8002
endpoints:
  druid:
    enabled: true
token:
  #  token过期时间，单位分钟
  tokenExpireTime: 5
  #  RefreshToken过期时间，单位：分钟
  refreshTokenExpireTime: 13
  #  shiro缓存有效期，单位分钟
  shiroCacheExpireTime: 5
  #  token加密密钥
  secretKey: storywebkey

redisson:
  mode: sentinel
  enable: true
  # 连接超时 毫秒
  connectTimeout: 10000
  # 命令等待超时
  timeout: 3000
  password: lindj
  # 客户端名称
  clientName: ${spring.application.name}
  # 主节点连接池大小
  masterConnectionPoolSize: 64
  # 主节点最小空闲连接数
  masterConnectionMinimumIdleSize: 32
  # 连接空闲超时
  idleConnectionTimeout: 10000
  # 重新连接时间间隔
  reconnectionTimeout: 3000
  # 从节点连接池大小
  slaveConnectionPoolSize: 64
  # 从节点最小空闲连接数
  slaveConnectionMinimumIdleSize: 32
  sentinelAddresses:
    - "redis://61.174.254.22:26379"
    - "redis://61.174.254.22:26378"
    - "redis://61.174.254.22:26377"
  database: 1
  masterName: lindj-master
